<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE productos [
<!ELEMENT productos (articulo+)>
<!ELEMENT articulo (nombre, precio, descripcion, calorias)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT calorias (#PCDATA)>
]>
<productos>
    <articulo>
      <nombre>Gofres Belgas</nombre>
      <precio>5,95</precio>
      <descripcion>Dos de nuestros famosos gofres belgas con abundante sirope</descripcion>
      <calorias>650</calorias>
    </articulo>
    <articulo>
      <nombre>Gofres Belgas con fresas</nombre>
      <precio>7,95</precio>
      <descripcion>Ligeros gofres belgas cubiertos de fresas y nata montada</descripcion>
      <calorias>900</calorias>
    </articulo>
    <articulo>
      <nombre>Gofres Belgas con frutas del bosque</nombre>
      <precio>8,95</precio>
      <descripcion>Ligeros gofres belgas cubiertos con frutas del bosque y nata montada</descripcion>
      <calorias>900</calorias>
    </articulo>
    <articulo>
      <nombre>Tostada francesa</nombre>
      <precio>4,50</precio>
      <descripcion>Dos gruesas rebanadas de nuestro pan francés casero</descripcion>
      <calorias>600</calorias>
    </articulo>
    <articulo>
      <nombre>Desayuno de la casa</nombre>
      <precio>6,95</precio>
      <descripcion>Dos huevos, bacon o salchicha, tostada y patatas fritas</descripcion>
      <calorias>950</calorias>
    </articulo>
</productos>