=== rsiles7/rsiles7.github.io/lm/tema7/a2/ejercicio4/ej4.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:sequence>
            <xs:element name="datos">
              <xs:complexType>
                <xs:sequence>
                  <xs:element name="nombre" type="xs:string"/>
                  <xs:element name="apellidos" type="xs:string"/>
                  <xs:element name="dni" type="xs:string"/>
                </xs:sequence>
              </xs:complexType>
            </xs:element>
            <xs:element name="comentario" type="xs:string"/>
          </xs:sequence>
          <xs:attribute name="fechanacimiento" type="xs:date" use="required"/>
        </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== rsiles7/rsiles7.github.io/lm/tema7/a2/ejercicio4/ej4.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas 
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="ej4.xsd"
>
<persona fechanacimiento="1599-02-08">
  <datos>
    <nombre>Antonio</nombre>  
    <apellidos>Rodríguez Sánchez</apellidos>
    <dni>12346789A</dni>
  </datos>
  <comentario>Alto, ojos claros...</comentario>
</persona>
<persona fechanacimiento="1598-12-31">
  <datos>
    <nombre>Antonia</nombre>  
    <apellidos>Sánchez Pérez</apellidos>
    <dni>987654321Z</dni>
  </datos>
  <comentario>baja, ojos oscuros...</comentario>
</persona>
</personas>
